### ISSUE TITLE
Create Group button

### ISSUE THREAD

**Issue by daveonche** [hypeJunction/Elgg-group_subtypes#1]
Hi Ismayil.....The 'Create Group' button disappears when the Group Subtypes Plugin is active and when deactivated, i get the raw language string 'groups:add:' Am testing with the latest version 1.0.2 on elgg 2.0.1.

**Comment by hypeJunction** [comment]
What do you "when deactivated"?
Did you configure your subtypes in Admin > Groups > Subtypes?
If you configure any Page identifier to be different from 'groups', you will see a lot of raw strings, the plugin doesn't translate those.

**Comment by daveonche** [comment]
Thanks, my bad...... I did not configure subtypes in Admin > Groups > Subtypes. It works fine now.
