### ISSUE TITLE
No 'Enable Subgroups' Checkbox in settings

### ISSUE THREAD

**Issue by dcrobertson01** [hypeJunction/Elgg-group_subtypes#2]
Hi - I've installed this on Elgg 2.2.3, and but I don't get the option to allow subgroups to be enabled in groups, as shown on your screen shots in the read me.

Is there something else I need to configure - have you tried it on elgg 2.2.3?

I'm using the 1.0.3 release. 

Cheers
Don

**Comment by hypeJunction** [comment]
Did you look under Groups > Subtypes in admin sidebar?

**Comment by dcrobertson01** [comment]
Hi - do you have another forum somewhere? I am sure I have answered this. Maybe I didn't hit save.

Yes, I have looked at the Groups > Subtypes page, and I get all the other options in the screenshot - just not the 'enable subgroups for this Group'

**Comment by hypeJunction** [comment]
Did you install AU subgroups and group subtype subgroups?

**Comment by dcrobertson01** [comment]
Okay, that did the trick. Didn't realise you need those modules as well.

**Comment by hypeJunction** [comment]
I do my best to list all suggested dependencies in the manifest, so either check there or view plugin info by clicking on its title

**Comment by dcrobertson01** [comment]
The manifest only lists elgg and groups as requirements.

**Comment by hypeJunction** [comment]
Ok. I will need to add the othets
